openapi: 3.0.3
info:
  title: partner API
  description: |-
    This is a super simple API for managing partners
  contact:
    email: devs@agile-learning.institute
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11

paths:
  /api/partners:
    post:
      summary: Add a new partner
      operationId: addPartner
      requestBody:
        description: Partner details to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Partner'
              required: true
      responses:
        '201':
          description: Partner added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Partner'
        '400':
          description: Bad request due to invalid input
    get:
      summary: Get a list of partners
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Partner'
        '404': 
          description: No partners found

  /api/partners/{partnerId}:
    get:
      summary: Get a partner by ID
      parameters:
        - name: partnerId
          in: path
          description: The ID of the partner to retrieve
          required: true
          schema:
            type: string
            format: GUID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Partner'
        '404':
          description: Partner not found

    patch:
      summary: Update a partner by ID
      parameters:
        - name: partnerId
          in: path
          description: The ID of the partner to update
          required: true
          schema:
            type: string
            format: GUID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Partner'
      responses:
        '200':
          description: Partner updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Partner'
        '404':
          description: Partner not found

  /api/partners/{partnerId}/contacts:
    post:
      summary: Add a new contact to a partner
      parameters:
        - name: partnerId
          in: path
          description: The ID of the partner to add the contact to
          required: true
          schema:
            type: string
            format: GUID
      requestBody:
        description: Details of the contact to be added
        required: true
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/Partner"
      responses:
        '200':
          description: Contact added successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Partner"
        '400':
          description: Bad request due to invalid input
        '404':
          description: Partner not found

  /api/partners/{partnerId}/contacts/{contactId}:
    delete:
      summary: Delete a contact from a partner
      parameters:
        - name: partnerId
          in: path
          description: The ID of the partner to delete the contact from
          required: true
          schema:
            type: string
            format: GUID
        - name: contactId
          in: path
          description: The ID of the contact to delete
          required: true
          schema:
            type: string
            format: GUID
      responses:
        '204':
          description: Contact deleted successfully
        '404':
          description: Partner or contact not found

  /api/enums/:
    get:
      summary: Get Enumerator Values
      operationId: getEnums
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Enums'          
  /api/config/:
    get:
      summary: Get API Configuration Information
      operationId: getConfig
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'    

  /api/health/:
    get:
      summary: Check API Health
      description: Returns information about the health of the API
      operationId: checkHealth
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Indicates the status of the API
                    enum:
                      - healthy
                      - unhealthy
                  details:
                    type: object
                    description: Additional details about the health status
                    properties:
                      uptime:
                        type: string
                        description: Time since the API started
                        example: "3 days, 2 hours, 15 minutes"
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message indicating why the service is unavailable
    

components:
  schemas:
    Partner:
      type: object
      properties:
        ID:
          type: string
          format: GUID
        name:
          type: string
        description:
          type: string
    Enums:
      type: object
      properties:
        ID:
          type: string
          format: GUID
        name:
          type: string
        enumerators:
          type: string
    Names: 
      type: array
      items:
        type: object
        properties: 
          ID:
            description: MongoDB _id
            type: string
            format: uuid
          name:
            description: Name
            type: string      
    Config:
      type: object
      properties:
        apiVersion:
          type: string
        dataVersion:
          type: string
        ConfigItems:
          type: array
          items:
            type: object
            properties: 
              name:
                description: Conf Item Name (Env Var Name, File Name)
                type: string
              value:
                description: The value for that config item
                type: string
              from:
                description: Where the value was found
                type: string
                enum:
                  - default
                  - environment
                  - file
    HealthStatus:
      type: object
      properties:
        status:
          type: string
          description: Indicates the status of the API
          enum:
            - healthy
            - unhealthy
        details:
          type: object
          description: Additional details about the health status
          properties:
            uptime:
              type: string
              description: Time since the API started
              example: "3 days, 2 hours, 15 minutes"
    HealthResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/HealthStatus'
        error:
          type: string
          description: Error message indicating why the service is unavailable
            