openapi: 3.0.3
info:
  title: partner API
  description: |-
    This is a super simple API for managing partners
  contact:
    email: devs@agile-learning.institute
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
paths:
  /api/partner/:
    post:
      summary: Add a new partner
      operationId: addPartner
      requestBody:
      
        description: Partner Name
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Partner'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Partner'          
        '405':
          description: Invalid input
    get:
      summary: Get a list of partner names and ids
      operationId: getNames
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Names'          
        '404':
          description: not found
        '405':
          description: Validation exception
  /api/partner/{id}:
    patch:
      summary: Update an existing partner
      description: Update an existing partner by Id
      operationId: updatePartner
      parameters:
        - name: id
          in: path
          description: ID of partner to update
          required: true
          schema:
            type: string
            format: GUID
      requestBody:
        description: Updated field
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Partner'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Partner'          
        '404':
          description: partner not found
        '405':
          description: Validation exception
    get:
      summary: Get an existing partner
      description: Get an existing partner by Id
      operationId: getPartner
      parameters:
        - name: id
          in: path
          description: ID of partner to return
          required: true
          schema:
            type: string
            format: GUID
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Partner'          
        '404':
          description: partner not found
        '405':
          description: Validation exception         
      
  /api/enums/:
    get:
      summary: Get Enumerator Values
      operationId: getEnums
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Enums'          
  /api/config/:
    get:
      summary: Get API Configuration Information
      operationId: getConfig
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'    
  /api/health/:
    get:
      summary: Check API Health
      description: Returns information about the health of the API
      operationId: checkHealth
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Indicates the status of the API
                    enum:
                      - healthy
                      - unhealthy
                  details:
                    type: object
                    description: Additional details about the health status
                    properties:
                      uptime:
                        type: string
                        description: Time since the API started
                        example: "3 days, 2 hours, 15 minutes"
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message indicating why the service is unavailable
      

components:
  schemas:
    Partner:
      type: object
      properties:
        ID:
          type: string
          format: GUID
        name:
          type: string
        description:
          type: string
    Enums:
      type: object
      properties:
        ID:
          type: string
          format: GUID
        name:
          type: string
        enumerators:
          type: string
    Names: 
      type: array
      items:
        type: object
        properties: 
          ID:
            description: MongoDB _id
            type: string
            format: uuid
          name:
            description: Name
            type: string      
    Config:
      type: object
      properties:
        apiVersion:
          type: string
        dataVersion:
          type: string
        ConfigItems:
          type: array
          items:
            type: object
            properties: 
              name:
                description: Conf Item Name (Env Var Name, File Name)
                type: string
              value:
                description: The value for that config item
                type: string
              from:
                description: Where the value was found
                type: string
                enum:
                  - default
                  - environment
                  - file